
Assignment Name -> B12-A5-Emergency-Hotline  
Repositories URL-> https://github.com/ProgrammingHero1/B12-A5-Emergency-Hotline  

আজকের মডিউল এ জাস্ট 1 টা ভিডিও থাকবে। অর্থাৎ এসাইনমেন্ট এ Main Requirements রিলেটেড কথাবার্তা।
এই এসাইনমেন্ট দিয়ে শেষ হবে তোমার ইন্টিগ্রেট জাভাস্ক্রিপ্ট মাইলস্টোন এর মেইন কাজ। তুমি যদি এই মাইলস্টোন
এর ব্যাসিকটা ভালো করে বুঝে থাক তাহলে এই এসাইনমেন্ট এর ৮০% তোমার জন্য পানি-ভাত হয়ে যাবে। তবে
এসাইনমেন্ট রিলেটেড জিনিসগুলো একটু ভালো করে বুঝে নাও। দরকার হলে এসাইনমেন্ট রিলেটেড ভিডিও দুই
তিনবার ভালো করে দেখে নাও। খাতায় ভালমত নোট করে নাও, তারপর আবার ভিডিও দেখে সব মিলিয়ে নাও
কোনটা বাদ পরলো কিনা।


অযথা ফেসবুক group এ এসে পোস্ট করে/ অন্যের করা পোস্ট দেখে কোনো কনফিউশন এ পরার দরকার নেই,
সময় নষ্ট করার দরকার নেই, বরং, assignment video কয়েকবার করে দেখ, তাহলেই কি করতে হবে, আর
কি করতে হবে না সেটা পানির মতো পরিষ্কার হয়ে যাবে।



এসাইনমেন্ট এ কি করতে হবে?

ভিডিওটা ভালো করে দেখো। কি কি করতে বলা হয়েছে নিজে নিজে পয়েন্ট বাই পয়েন্ট লিস্ট বানিয়ে চিন্তা করো।
কেউ রিকোয়ারমেন্ট বলে দিলে সেই অনুসারে লিস্ট বানিয়ে ফেলা খুবই দরকারি একটা হ্যাবিট। কারণ অফিসে বা
অনেক সময় ক্লায়েন্ট মিটিংয়ে ফিডব্যাক বলে দিবে। তোমাকে সেগুলা লিষ্ট করে নিতে হবে। বুঝে নিতে হবে। এখন
একটু কষ্ট হলেও। ফিউচারে এইসব সিচুয়েশন তোমার কাছে ডাল-ভাত হয়ে যাবে। চ্যালেঞ্জ মার্কস কিসের উপরে,
কয়টা জিনিসের উপর নির্ভর করবে সেটাও ভালো করে এসাইনমেন্ট এর ভিডিও তে দেখে ফেলো।



এসাইনমেন্ট রিলেটেড হেল্প:

যেহেতু এইটা এসাইনমেন্ট। তাই চেষ্টা করবে এসাইনমেন্ট রিলেটেড কোন হেল্প না নিয়ে ১০০% নিজে নিজে করো।
দরকার হলে আগের ভিডিও দেখো। গুগলে সার্চ দাও। Chat Gpt ও করতে পারো। তবে full copy কোথাও থেকে
করবেনা। তাহলে copy detected হয়ে ধরা খাবে আর জিরো পাবে, তখন শত কান্নাকাটি করলেও আর কোনও লাভ
হবেনা।আর একান্তই আটকে গেলে, এসাইনমেন্ট এর ক্ষেত্রে "এইটা কিভাবে করবো" বা "এইটা করে দেন" সেই
রিলেটেডহেল্প চাওয়া যাবে না। কারণ তোমার এসাইনমেন্ট এর কাজ আরেকজন করে দিলে তোমার পরিপূর্ণ শেখা হলো
না। তবে আমি এইটা করছি-- এইটা এইভাবে কাজ করার কথা। কিন্তু কাজ করছে না কেন? সেই টাইপের হেল্প চাইতে
পারবে।



আর তোমরা যারা অন্যদের হেল্প করতেছো। এইটা খুবই ভালো। সবসময় বিস্তারিত লিখে হেল্প করবে। তবে এসাইনমেন্ট
চলাকালীন সময় শুধু হিন্টস দিবে। এসাইনমেন্ট রিলেটেড সরাসরি হেল্প করো না। অন্য সময় সরাসরি হেল্প করতে পারবে।
এসাইনমেন্ট এর সময় সরাসরি উত্তর বলে দিলে আমরা তাকে মিউট করবো।



কি সাবমিট করতে হবে?

১। গিটহার রিপোজিটরি লিংক।

২। লাইভ সাইট লিংক।



সঠিকভাবে সঠিক সময়ে সাবমিট:

একবার এসাইনমেন্ট সাবমিট করে দিলে সেটাই ফাইনাল। ভুল রিপজিটরি এর লিংক দিয়ে দিলে। কিংবা রাত ১১.৫৯ মিনিটে
তোমার কিবোর্ডের উপর তেলাপোকা উড়ে এসে বসলে কিংবা ওয়াইফাই রাউটার কাশি দিলে। এইসব কারণে এসাইনমেন্ট সাবমিট
করতে ডিলে হলে আমাদের কিছু করার থাকবে না। সো, কারেন্ট এবং নেট থাকার সময়েই এসাইনমেন্ট সাবমিট করে ফেলো।



আর একান্তই চেইঞ্জ করতে চাইলে রিসাবমিট করতে পারবে।


সততা:

চালাকি কিংবা শর্টকাট তুমি চাইলে অনেক সময় করতে পারবে। এতে হয়তো দুই-চার মার্কস বেশি পেলেও পেয়ে যেতে পারো।
তবে সেটা কিন্তু আল্টিমেটলি তোমার ক্ষতি করবে। তাই একটু কষ্ট করে বুঝে বুঝে নিজের চেস্টায় যদি ১০ মার্কস কম পাও।
সেটাই হবে তোমার সততার অর্জন। চালাকি করে ১০ মার্কস পাওয়ার চাইতে সৎ হিসেবে ১০ মার্কস কম পাওয়াও অনেক গর্বের।



ওয়ার্নিং:

ফেসবুক এ এসাইনমেন্ট মার্ক্স/ ফিডব্যাক রিলেটেড পোস্ট দেওয়া যাবেনা। কোন confusion থাকলে আমাদেরকে মেইল করো
বা সাপোর্ট সেশন এ গিয়ে তুমি তোমার এসাইনমেন্ট নিয়ে ডিসকাস করতে পারো।



এসাইনমেন্ট ডেডলাইন + মার্কস:

২৯ আগস্ট, রাত ১১.৫৯ (বাংলাদেশ সময়) এর মধ্যে তোমার এসাইনমেন্ট জমা দিলে তোমার সর্বোচ্চ মার্কস হবে ৬০ মার্কস,
এবারের জন্য ৫০ মার্কের ডেডলাইন থাকছে না। deadline শেষ হবার পর যেইদিন ই তুমি assignment submit করো তোমার
সর্বোচ্চ মার্কস হবে ৩০ মার্কস।